Add .NET 6.0 target (#40)
Motivation
----------
Allow the use of .NET 6 specific optimizations and use the latest SDK
to build.

Modifications
-------------
- Add a .NET 6 target to the library
- Fix conditional compilation directives to correctly include .NET 6
- Switch unit tests from .NET 5 to 6
- Upgrade build scripting to use the .NET 6 SDK.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,7 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        framework: ["net5.0", "netcoreapp3.1", "netcoreapp2.1"]
+        framework: ["net6.0", "netcoreapp3.1", "netcoreapp2.1"]
         disable: ["HWIntrinsics", "SSSE3", "BMI2", "Noop"]
         exclude:
           - framework: "netcoreapp2.1"
@@ -24,10 +24,10 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
-    - name: Setup .NET 5.0
+    - name: Setup .NET 6.0
       uses: actions/setup-dotnet@v1
       with:
-        dotnet-version: '5.0.x'
+        dotnet-version: '6.0.x'
     - name: Setup .NET Core 3.1
       if: matrix.framework == 'netcoreapp3.1'
       uses: actions/setup-dotnet@v1
@@ -38,26 +38,30 @@ jobs:
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: '2.1.x'
+    # Cache packages for faster subsequent runs
+    - uses: actions/cache@v2
+      with:
+        path: ~/.nuget/packages
+        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
+        restore-keys: |
+          ${{ runner.os }}-nuget-
 
     - name: Install dependencies
       run: dotnet restore
+    - name: Build
+      run: dotnet build --configuration Release --verbosity normal
     - name: Test
       run: |
         export COMPlus_Enable${{ matrix.disable }}=0 && \
-        dotnet test -f ${{ matrix.framework }} --configuration Release --verbosity normal --logger "junit;LogFilePath=test-results/results.xml"
+        dotnet test --no-build -f ${{ matrix.framework }} --configuration Release --verbosity normal --logger "trx;LogFileName=results.trx"
 
-    - name: Publish Unit Test Results
-      uses: EnricoMi/publish-unit-test-result-action@f8a3fca6035d817e664cd0bf57d7fefc407847ee # pre-1.4, adds comment_on_pr option
-      if: >
-        github.event_name == 'push' ||
-        github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # run this step even if previous step failed
       with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        check_name: Unit Tests ${{ matrix.framework }} Enable${{ matrix.disable }}=0
-        files: '**/test-results/**/*.xml'
-        report_individual_runs: true
-        comment_on_pr: false
-
+        name: Unit Tests
+        path: "**/results.trx"
+        reporter: dotnet-trx
 
   publish:
 
@@ -67,10 +71,10 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
-    - name: Setup .NET 5.0
+    - name: Setup .NET 6.0
       uses: actions/setup-dotnet@v1
       with:
-        dotnet-version: '5.0.x'
+        dotnet-version: '6.0.x'
 
     - name: Install dependencies
       run: dotnet restore
